---
- block:
    - name: Install Suricata-update
      pip:
        name: suricata-update
        virtualenv: "{{ virtual_env_dir }}"
        extra_args: --upgrade --upgrade-strategy eager
        virtualenv_command: python3 -m venv
      become: no
      register: results
      environment:
        http_proxy: "{{ http_proxy_env |d() }}"
        https_proxy: "{{ https_proxy_env |d() }}"

    - name: Suricata-update installation without a proxy results
      debug:
        msg: "{{ results.stdout_lines }}"

    ### This needs to be tested to determine if it is still needed ####
    # # Install Suricata-update behind a proxy
    # - name:                 Install Suricata-update with sudo -H behind a proxy
    #   shell: |
    #     sudo -H pip3 install --upgrade --prefix=/usr/local --upgrade-strategy only-if-needed --proxy {{ https_proxy_env }} suricata-update
    #   register:             results
    #   args:
    #     warn:               no
    #   when:                 https_proxy_env is defined

    # - name:                 Suricata-update installation with a proxy results
    #   debug:
    #     msg:                "{{ results.stdout_lines }}"
    #   when:                 results is not skipped

    - name: Create directories
      file:
        path: "{{ item.dir }}"
        state: directory
        mode: "0775"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop:
        - { dir: "/var/lib/suricata" }
        - { dir: "{{ suricata_dir }}" }
        - { dir: "{{ suricata_update_dir }}" }
        - { dir: "{{ suricata_update_output_dir }}" }
        - { dir: "{{ suricata_custom_rules_dir }}" }

    - name: Create /var/corelight/suricata directory
      file:
        path: /var/corelight/suricata
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Include Suricata-update on a Software Sensor Install Tasks
      include_tasks: sensor-install.yml
      when: "'software_sensors' in group_names"

  always:
    - name: "[zkgi-4] Include set role facts tasks"
      include_tasks: "{{ role_path }}/../common/tasks/set-role-facts.yml"
      vars:
        fact_section: suricata_update
        fact_option: install
        fact_value: success
        failed_task: none
        failed_state: absent
      when: ansible_failed_task is not defined

  rescue:
    - name: "[zkgi-5] Include set role failed facts tasks"
      include_tasks: "{{ role_path }}/../common/tasks/set-role-facts.yml"
      vars:
        fact_section: suricata_update
        fact_option: install
        fact_value: failed
        failed_task: "{{ ansible_failed_task.name }}"
        failed_state: present
      when: ansible_failed_task is defined

    - name: "[zkgi-6] Failed task"
      fail:
        msg: |
          "{{ ansible_failed_result.stderr_lines | to_nice_yaml }}"
