---
- name: Touch files for symbolic links to corelight-suricata
  file:
    path: "/var/corelight/suricata/{{ item.src }}"
    state: touch
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - { src: classification.config }
    - { src: reference.config }
    - { src: threshold.config }
    - { src: suricata.socket }

- name: Create symbolic links to corelight-suricata
  file:
    src: "/var/corelight/suricata/{{ item.src }}"
    dest: "{{ suricata_dir }}/{{ item.dest }}"
    mode: '0644'
    state: hard
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - { src: classification.config, dest: classification.config }
    - { src: reference.config, dest: reference.config }
    - { src: threshold.config, dest: threshold.config }
    - { src: suricata.socket, dest: suricata.socket }
