---
- name:           create bundle
  shell:          zkg bundle ansible_role.bundle --force
  args:
    chdir:        "{{ role_path }}/files"
  when:
    - 'zeek_packages != None'
    - ( install_depends.changed or remove_pkgs.changed or upgrade_pkgs.changed )
  register:       create_bundle
  delegate_to:    localhost
  run_once:       true
