---
#Use Corelight-Client to upload the list to the Input Framework for non-fleet managed physical or virtual sensors
- name:         Upload trusted_domains.csv list to non-fleet managed physical or virtual sensors
  command:      corelight-client -b "{{ ansible_host }}" -u "{{ sensor_username }}" -p "{{ sensor_password }}" --no-password-save --ssl-no-verify-certificate bro input upload --name trusted_domains.dat --file ./source_files/trusted_domains.dat
  delegate_to:  localhost
  when:
    - trusted.changed
    - ('physical_sensors' in group_names or 'virtual_sensors' in group_names)
    - (fleet == 'n' or fleet == "no")
  become:       false

#Use Corelight-Client to upload the list to the Input Framework for fleet managed physical or virtual sensors
- name:         Upload trusted_domains.csv list to fleet managed physical or virtual sensors
  command:      corelight-client --fleet "{{ fleet_ip }}" --uid "{{ UID }}" -u "{{ sensor_username }}" -p "{{ sensor_password }}" --no-password-save --ssl-no-verify-certificate bro input upload --name trusted_domains.dat --file ./source_files/trusted_domains.dat
  delegate_to:  localhost
  when:
    - trusted.changed
    - ('physical_sensors' in group_names or 'virtual_sensors' in group_names)
    - (fleet == 'y' or fleet == "yes")
  become:       false