---
- hosts: localhost
  gather_facts: no
  become: yes

  tasks:
    - include_role:
        name: common
      vars:
        role_name_fact:
          - venv_setup
          - zkg_install
          - corelight_client_install
          - ansible_install
          - suricata_update_install
          - suricata_update_config
          - suricata_config_cron_job

- hosts: main_hosts
  debugger: never
  strategy: host_pinned
  become: yes
  gather_facts: no

  tasks:
    - name: Gather Facts
      setup:
      when:
        - "'physical_sensors' not in group_names"

    - name: "[plbk-3] Include common role to CHECK FACTS"
      import_role:
        name: common
      vars:
        starting_role: none

    - name: Include Python3 virtual environment setup role
      include_role:
        name: venv_setup
      when:
        - "ansible_local.corelight_ansible_roles.venv.setup|d('failed') == 'failed'"

    - name: Include ZKG install role
      include_role:
        name: zkg_install
      when:
        - "ansible_local.corelight_ansible_roles.zkg.install|d('failed') == 'failed'"

    - name: Include Corelight-client install role
      include_role:
        name: corelight_client_install
      when:
        - "ansible_local.corelight_ansible_roles.corelight_client.install|d('failed') == 'failed'"

    - name: Include Ansible install role
      include_role:
        name: ansible_install
      when:
        - "ansible_local.corelight_ansible_roles.ansible.install|d('failed') == 'failed'"

    - name: Include Suricata-update install role
      include_role:
        name: suricata_update_install
      when:
        - "ansible_local.corelight_ansible_roles.suricata_update.install|d('failed') == 'failed'"
        - "inventory_hostname == suricata_update_host"

    - include_role:
        name: suricata_update_config
      when:
        - "ansible_local.corelight_ansible_roles.suricata_update.config|d('failed') == 'failed'"
        - inventory_hostname == suricata_update_host

    - include_role:
        name: suricata_config_cron_job
      when:
        - "ansible_local.corelight_ansible_roles.suricata_update_cron_job.config|d('failed') == 'failed'"
        - inventory_hostname == cron_job_host
        - perform_cron_job_tasks|d(true) is true
