---
- hosts: localhost
  gather_facts: no
  become: yes

  tasks:
    - name: Include common role
      include_role:
        name: common
      vars:
        role_name_fact:
          - venv_setup
          - zkg_install
          - software_sensor_install
          - software_sensor_config
          - suricata_update_install
          - suricata_update_config
          - suricata_config_cron_job

    - name: add host to dynamically_created_hosts group
      add_host:
        name: "{{ item }}"
        groups: dynamically_created_hosts
      changed_when: false
      when:
        - "'software_sensors' in groups"
      with_items: "{{ groups['software_sensors'] }}"

- hosts: dynamically_created_hosts
  become: yes
  gather_facts: no

  tasks:
    - name: Gather Facts
      setup:
      when:
        - "'software_sensors' in group_names"

    - name: "[plbk-3] Include common role to create groups"
      import_role:
        name: common
      vars:
        sending_role: none

    - name: Include Python3 virtual environment setup role
      include_role:
        name: venv_setup
      when:
        - "ansible_local.corelight_ansible_roles.venv.setup|d('failed') == 'failed'"

    - name: Include ZKG install role
      include_role:
        name: zkg_install
      # when:
      #   - "ansible_local.corelight_ansible_roles.zkg.install|d('failed') == 'failed'"

    - name: Include Software Sensor Install role
      include_role:
        name: software_sensor_install
      # when:
      #   - "ansible_local.corelight_ansible_roles.softsensor.install|d('failed') == 'failed'"

    - name: Include Suricata-update install role
      include_role:
        name: suricata_update_install
      when:
        # - "ansible_local.corelight_ansible_roles.suricata_update.install|d('failed') == 'failed'"
        - "suricata_update_enable|d('disabled') == 'local'"
        - "suricata_enable|d(false) is true"

    - name: Include Software Sensor Config role
      include_role:
        name: software_sensor_config
      # when:
      #   - "ansible_local.corelight_ansible_roles.softsensor.config|d('failed') == 'failed'"

    - name: "[ ] Include zkg role"
      include_role:
        name: zkg
      vars:
        starting_role: software_sensor_config
      # when:
        # - "zkg_last_run.inventory_hostname.last_run_results|d('failed') == 'failed'"

    - name: Include Suricata-update config role
      include_role:
        name: suricata_update_config
      when:
        # - "ansible_local.corelight_ansible_roles.suricata_update.config|d('failed') == 'failed'"
        - "suricata_update_enable|d('disabled') == 'local'"
        - "suricata_enable|d(false) is true"

    - name: "[ ] Gather Facts for suricata-update run"
      setup:
        filter: ansible_local
        gather_subset: "!all"
      when:
        - "inventory_hostname == suricata_update_host or
          'suricata_local' in group_names or
          'suricata_remote' in group_names"
        - "'physical_sensors' not in group_names"

    - name: Include Suricata-update run role
      include_role:
        name: suricata_update_run
      when:
        - "ansible_local.corelight_ansible_roles.suricata_update.config|d('failed') == 'success'"
        - "suricata_update_enable|d('disabled') == 'local'"
        - "suricata_enable|d(false) is true"

    - name: Include Suricata-update config cron job role
      include_role:
        name: suricata_config_cron_job
      when:
        # - "ansible_local.corelight_ansible_roles.suricata_update_cron_job.config|d('failed') == 'failed'"
        - "suricata_update_enable|d('disabled') == 'local'"
        - "suricata_enable|d(false) is true"
