---
- hosts: localhost
  gather_facts: no
  become: yes

  tasks:
    - name: "[plbk-1] Include common role"
      include_role:
        name: common
      vars:
        role_name_fact:
          - software_sensor_config

    - name: "[plbk-2] Include software_sensors members in dynamically_created_hosts"
      add_host:
        name: "{{ item }}"
        groups: dynamically_created_hosts
      changed_when: false
      when:
      with_items: "{{ groups['software_sensors'] }}"

- hosts: dynamically_created_hosts
  become: yes
  gather_facts: no

  tasks:
    # - name: "[plbk-3] Include common role to CHECK FACTS"
    #   import_role:
    #     name: common
    #   vars:
    #     sending_role: software_sensor_config

    - name: "[plbk-3] "
      include_role:
        name: software_sensor_config
