---
- hosts: all
  gather_facts: no
  become: yes
  vars_prompt:
  - name: target
    prompt: Please enter the target host name or group name
    private: no


  tasks:
    - include_role:
        name: corelight-software-sensor
      when:
        - "'software_sensors' in group_names"
        - (target == inventory_hostname or target == 'all')
