---
- hosts:                  localhost
  gather_facts:           no
  become:                 yes
  vars_prompt:
  - name:                 target
    prompt:               Please enter the target host name or group name
    private:              no

  tasks:
    - include_role:
        name:             zkg
    - set_fact:
        target_system:    "{{ target }}"
      changed_when:       false

- hosts:                  all
  become:                 yes
  gather_facts:           no
  vars:
    - target:             "{{ hostvars['localhost']['target_system'] }}"

  tasks:
    - include_role:
        name:             zkg
      when:
        - ('physical_sensors' in group_names or 'virtual_sensors' in group_names)
        - (target == inventory_hostname or target == 'all')
