---
- name: Reload Suricata rules Debian
  shell: kill -USR2 $(pidof corelight-suricata)
  args:
    executable: /bin/bash
  become: yes
  when: ansible_os_family == 'Debian'

# - name:           Reload Suricata rules RHEL
#   service:
#     name:         corelight
#     state:        restarted
#   become:         yes
#   when:           ansible_os_family == 'RedHat'

- name: Reload Suricata rules RHEL
  shell: kill -USR2 $(pidof corelight-suricata)
  args:
    executable: /bin/bash
  become: yes
  when: ansible_os_family == 'RedHat'
