---
- name: Collect list of existing custom rules
  find:
    paths: "{{ suricata_custom_rules_dir }}"
    file_type: file
    patterns: "*.rules"
  register: existing_rule_file_list

- name: Write rule file list to a file
  template:
    src: "remove-rule-file-list.yaml.j2"
    dest: "{{ role_path }}/vars/{{ inventory_hostname }}-remove-rule-file-list.yaml"
    mode: '0644'
    owner: "{{ hostvars['localhost'].ansible_user }}"
    group: "{{ hostvars['localhost'].ansible_user }}"
  delegate_to: localhost
  changed_when: false
