---
- name: "[suc-9-1] Collect list of existing custom rules"
  find:
    paths: "{{ suricata_rules_dir }}"
    file_type: file
    patterns: "*.rules"
  register: existing_rule_file_list

- name: "[suc-9-2] Write rule file list to a file"
  template:
    src: "remove-rule-file-list.yaml.j2"
    dest: "{{ role_path }}/vars/{{ inventory_hostname }}-remove-rule-file-list.yaml"
    mode: '0644'
    owner: "{{ hostvars['localhost'].ansible_user }}"
    group: "{{ hostvars['localhost'].ansible_user }}"
  delegate_to: localhost
  changed_when: false

########TEMP#DEBUG######
- debug:
    msg: |
      sensor
      "{{ inventory_hostname }}"
      "{{ existing_rule_file_list | to_nice_yaml }}"
  tags: [ never, debug ]
- pause:
    prompt:
  tags: [ never, debug ]
######################
