---
secrets_path:                           "../../../common/secrets.yml"
inventory_path:                         "../../../common/inventory.yml"
main_vars_path:                         "../../../common/main-vars.yml"

# Corelight-Suricata Settings
suricata_enable:                        false

# fleet_managed enable or disable
fleet_managed:                          disable
fleet_ip:
UID:
### Cron Job Variables ###
# To enable the cron job on any system other than localhost,
# the target system MUST have 'suricata_update_enable' set to 'local'.
enable_cron:                            false     # true or false
cron_job_target:                        all       # name of the group or host sensor for Suricata-update

#### Suricata Variables ####
# Suricata Settings
suricata_rule_path:                     /etc/corelight/rules

#### Suricata-update Variables ####

# Use Suricata-update should be set in the inventory file for each sensor.
# If it's not listed, the default will apply.
# options are:
# local = use suricata-update in this ansible role
# remote = use suricata-update from another source
# disabled = don't use suricata-update
suricata_update_enable:                 disabled

# Path to Suricata-update config and rule files
suricata_update_path:                   /etc/corelight/suricata-update

# Custom rules will be placed in suricata_custom_rules_path
# Suricata-update will collect the custom rules and combine them with the downloaded rules

# Path to custom Suricata rules for Suricata-update
suricata_custom_rules_path:             /etc/corelight/suricata-update/custom-rules
