---
virtual_env_dir: /etc/corelight-env
validate_certs: yes

fleet_managed: false
fleet_ip:
UID:

###################################
#### Suricata-update Variables ####
###################################
lawmaker_enabled: false
lawmaker_url: "https://api.lawmaker.cloud"

# DO NOT USE 'localhost' AS THE suricata_update_host, instead list the host name in the
# inventory file and add 'ansible_connection: local'
suricata_update_enable: disabled
suricata_update_host: # The host name to run Suricata-update on

suricata_dir: /usr/local/etc/suricata # The default directory for suricata config files
suricata_update_dir: /etc/suricata # The default directory where suricata-update looks for config files
suricata_update_output_dir: /var/lib/suricata/rules # The default directory where suricata-update puts suricata.rules
suricata_rules_dir: /var/lib/suricata/rules # The directory where corelight-suricata looks for rulesets
suricata_custom_rules_dir: /etc/suricata/rules # The directory where suricata-update looks for local rules

############################################
#### Suricata-update Cron Job Variables ####
############################################
# NOTE: This role will only create a cron job task on the
# local ansible controller or the 'suricata_update_host'

### cron_job_tasks is an administrative setting
# cron_job_tasks options are:
# enabled = cron_job_tasks will be executed
# disabled = cron_job_tasks will be skipped
# only = all non-cron_job_tasks will be skipped.  Use if you just want to update the cron_job date/time
cron_job_tasks: enabled

enable_cron_job: true # true or false, enables or disables the cron job
cron_job_hour: "0" # 0-23
cron_job_minute: "0" # 0-59
cron_job_target: all # name of the group or host sensor for Suricata-update
cron_job_log_path: "/var/log/suricata_update"
cron_job_host:
# NOTE: only use 'localhost' for the cron_job_host when Ansible and the cron job are local and Suricata-update is on a remote host

######################################
#### Corelight-Suricata Variables ####
######################################

# Corelight-Suricata Settings
suricata_enable: false

# If Suricata-update is enable, custom rules will be placed in suricata_custom_rules_dir
# Suricata-update will collect the custom rules and combine them with the downloaded rules
# If Suricata-update is NOT enabled, custom rules will be placed in suricata_rule_path
#suricata_custom_rules_dir: (same as suricata-update variables above)   # The directory where suricata-update looks for local rules
#suricata_rules_dir: (same as suricata-update variables above)  # The directory where corelight-suricata looks for rulesets
suricata_rule_files: "*.rules"

#######################################
#### Zeek Script Package Variables ####
#######################################

corelight_packages:

included_packages:

zeek_packages:

###################################
#### Software Sensor Variables ####
###################################

# You only need to set the system_name value if the hostname is
# not an acceptable name to use in the logs and other export locations.
corelight_repo_url:
corelight_release_branch: stable

enable_custom_system_name: false
corelight_system_name: corelight-sniff01

num_workers: 2
sniff_interfaces: eth0

corelight_disk_space: /var/corelight
corelight_share_stats: true
local_networks: 10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,100.64.0.0/10,127.0.0.0/8,fe80::/10,::1/128
load_scripts: /etc/corelight/local.zeek
ignore_bpf:
memory_limit: 6500

# Analyzer Specific Settings
archive_expand_enable: false

# HEC Configuration
hec_enable: false
hec_url: https://mysplunk.com:8088/services/collector
hec_token:
hec_sourcetype_prefix: corelight_
hec_verify_cert: true
hec_writer_verbose: false # enable debugging

# Kafka Configuration
kafka_enable: false
kafka_servers: 1.2.3.4:9092
kafka_topic_prefix:
kafka_enable_ssl: true
kafka_sasl_username:
kafka_sasl_password:
kafka_ssl_ca_location:

# JSON over TCP Configuration
json_enable: false
json_server: 1.2.3.4:12345

# JSON over TCP Syslog Config
syslog_enable: false
syslog_server: 1.2.3.4:514
syslog_facility: local0
syslog_severity: info
syslog_format: rfc5424_octet_framing

# Redis Configuration
redis_enable: false
redis_host: 127.0.0.1
redis_port: 6379
redis_password:
redis_key_prefix: corelight-

# Batch Log Configuration
batch_log_format: json
batch_log_rotation_interval: 3600
batch_log_gzip: false

batch_log_disk_enable: true
batch_log_disk_path: ./logs
batch_log_disk_cleanup_enable: false
batch_log_disk_cleanup_pct_max: 80

batch_log_ssh_enable: false
batch_log_ssh_mode: sftp
batch_log_ssh_server: 1.2.3.4
batch_log_ssh_port: 22
batch_log_ssh_user: username
batch_log_ssh_password:
batch_log_ssh_privkey:
batch_log_ssh_privkey_passphrase:
batch_log_ssh_path: ./corelight-logs

# File Extraction Configuration
extracted_files_max_bytes: 5242880
extracted_files_filter:

extracted_files_mime_types:
extracted_files_group_archives: true
extracted_files_group_executables: true
extracted_files_group_flash: true
extracted_files_group_java: true
extracted_files_group_office_documents: true
extracted_files_group_pdfs: true

extracted_files_disk_enable: false
extracted_files_disk_directory: ./extracted_files
extracted_files_disk_cleanup_enable: false
extracted_files_disk_cleanup_pct_max: 80

extracted_files_ssh_enable: false
extracted_files_ssh_mode: sftp
extracted_files_ssh_server: 1.2.3.4
extracted_files_ssh_port: 22
extracted_files_ssh_user: username
extracted_files_ssh_password:
extracted_files_ssh_privkey:
extracted_files_ssh_privkey_passphrase:
extracted_files_ssh_path: ./corelight-extracted-files

# Metrics Configuration
prometheus_enable: false
prometheus_metrics_per_process: false
prometheus_listen: "127.0.0.1:8989"
