---
- name:           restart software sensor
  service:
    name:         corelight
    state:        restarted

- name:           Reload Suricata rules
  shell:          kill -USR2 $(pidof corelight-suricata)
  args:
    executable:   /bin/bash
  become:         yes
