---
- name:             "suricata-rules-clients: Copy Suricata-update Rules to software sensors"
  copy:
    src:            "{{ suricata_update_path }}/rules/{{ suricata_version }}/suricata.rules"
    dest:           "{{ suricata_rule_path }}"
    mode:           0644
  when:
    - "'software_sensors' in group_names"
  notify:           Reload Suricata rules
  register:         results2

- debug:
    var:            results2.stdout_lines

- name:             "suricata-rules-clients: Push Suricata-update Rules to Physical or Virtual sensors"
  command:          corelight-client -b "{{ ansible_host }}" -u "{{ sensor_username }}" -p "{{ sensor_password }}" --no-password-save --ssl-no-verify-certificate suricata ruleset upload --filename suricata.rules --file {{ suricata_update_path }}/rules/{{ suricata_version }}/suricata.rules
  delegate_to:      localhost
  become:           no
  when:
    - "'software_sensors' not in group_names"
    - fleet_managed == 'disable'
  register:         results3

- debug:
    var:            results3.stdout_lines

- name:             "suricata-rules-clients: Push Suricata-update Rules to Fleet Managed Physical or Virtual sensors"
  command:          corelight-client --fleet "{{ fleet_ip }}" --uid "{{ UID }}" -u "{{ sensor_username }}" -p "{{ sensor_password }}" --no-password-save --ssl-no-verify-certificate suricata ruleset upload --filename suricata.rules --file "{{ suricata_update_path }}/rules/{{ suricata_version }}/suricata.rules"
  delegate_to:      localhost
  become:           no
  when:
    - "'software_sensors' not in group_names"
    - fleet_managed == 'enable'
  register:         results4

- debug:
    var:            results4.stdout_lines
