---
- name:             "suricata-rules-clients: Copy Suricata-update Rules to software sensors"
  copy:
    src:            "{{ suricata_update_path }}/rules/{{ suricata_version }}/suricata.rules"
    dest:           "{{ suricata_rule_path }}"
    mode:           0644
  when:
    - "'software_sensors' in group_names"
  notify:           Reload Suricata rules
  register:         results

- debug:
    msg:            results

- name:             "suricata-rules-clients: Push Suricata-update Rules to Physical or Virtual sensors"
  shell:            corelight-client -b "{{ ansible_host }}" -u "{{ sensor_username }}" -p "{{ sensor_password }}" --no-password-save --ssl-no-verify-certificate suricata ruleset upload --filename suricata.rules --file {{ suricata_update_path }}/rules/{{ suricata_version }}/suricata.rules
  delegate_to:      localhost
  when:
    - "'software_sensors' not in group_names"
    - fleet_managed == 'disable'
  register:         results

- debug:
    msg:            results

- name:             "suricata-rules-clients: Push Suricata-update Rules to Fleet Managed Physical or Virtual sensors"
  shell:            corelight-client --fleet "{{ fleet_ip }}" --uid "{{ UID }}" -u "{{ sensor_username }}" -p "{{ sensor_password }}" --no-password-save --ssl-no-verify-certificate suricata ruleset upload --filename suricata.rules --file "{{ suricata_update_path }}/rules/{{ suricata_version }}/suricata.rules"
  delegate_to:      localhost
  when:
    - "'software_sensors' not in group_names"
    - fleet_managed == 'enable'
  register:         results

- debug:
    msg:            results
