---
- name:             "suricata-update-local: Run Suricata-update"
  command:          suricata-update --no-reload --no-test -c "{{ suricata_update_path }}/update.yaml" 
  become:           no
  register:         results1
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"

- debug:
    var:          results1.stdout_lines

- name:             "suricata-update-local: Copy Suricata-update Rules to Corelight-Suricata Rule folder"
  copy:
    src:            "{{ suricata_update_path }}/rules/suricata.rules"
    dest:           "{{ suricata_rule_path }}"
    mode:           0644
