---
- name:             Load vars
  include_vars:
    file:           '{{ item }}'
  with_items:
    - "{{ secrets_path }}"
    - "{{ main_vars_path }}"

- name:             "main: Gather Software Sensor facts"
  setup:
  when:
    - ('software_sensors' in group_names or 'suricata_update_host' in group_names)

- name:             Include Debian Tasks
  include_tasks:    debian.yml
  when:
    - "ansible_os_family == 'Debian'"
    -  sensor_update_only is false

- name:             "main: Include RHEL Tasks"
  include_tasks:    redhat.yml
  when:
    - "ansible_os_family == 'RedHat'"
    -  sensor_update_only is false

- name:             "main: Include Software Sensor Common Tasks"
  include_tasks:    software_sensor_common.yml
  when:
    - "'software_sensors' in group_names"
    - sensor_update_only is false

- name:             "main: Include Software Sensor Update Only Tasks"
  include_tasks:    software_sensor_update_only.yml
  when:             sensor_update_only is true