---
# Install zkg dependencies
- name:           "redhat: Install pip3"
  yum:
    name:         python3-pip
    state:        latest

- name:           "CentOS7: Enable CentOS Extra repos"
  yum:
    name:         epel-release
    state:        latest
  when: 
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version == '7'"

- name:           "CentOS7: Install python-setuptools"
  yum:
    name:         python-setuptools
    state:        latest
  when: 
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version == '7'"

- name:           "CentOS7: Install pip2"
  yum:
    name:         python-pip
    state:        latest
  when: 
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version == '7'"

- name:           "redhat: Install git"
  yum:
    name:         git
    state:        latest

- name:           "redhat: Install zkg"
  pip:
    name:         zkg
    state:        latest
    executable:   pip3

- name:           "redhat: Check for zkg in sudoers path"
  lineinfile:
    path:         /etc/sudoers
    regexp:       '^(Defaults\s+secure_path\s+=\s+)(.*:)?/usr/local/bin(:.*)?$'
    state:        absent
  check_mode:     yes
  changed_when:   false
  register:       sudoers_path

- name:           "redhat: Add zkg to sudoers path"
  lineinfile:
    path:         /etc/sudoers
    regexp:       '^(Defaults\s+secure_path\s+=\s+.*)$'
    line:         '\1:/usr/local/bin'
    state:        present
    create:       yes
    mode:         u=wrx,g=rx,o=rx
    backrefs:     yes
  when:           not sudoers_path.found

- name:           Reset connection to enable PATH change
  meta:           reset_connection
  changed_when:   false

- name:           "redhat: Add Corelight Package Signing Key | RHEL"
  rpm_key:
    key:          https://{{ corelight_repo_url }}/signing.pub
    state:        present

# Only one release branch will be in the sources list at a time
- name:             "redhat: Create Repository List"
  template:
    src:            corelight.repo.j2
    dest:           /etc/yum.repos.d/Corelight-Repository.repo
    owner:          root
    group:          root
    mode:           644
  register:         repo

- name:           "redhat: yum-clean-metadata"
  command:        yum clean metadata
  args:
    warn:         no
  when:           repo.changed

- name:           "redhat: Remove Corelight Software Sensor"
  yum:
    name:         corelight
    update_cache: yes
    state:        absent
    autoremove:   yes
  when:           repo.changed

- name:           "redhat: Install Corelight Software Sensor"
  yum:
    name:         corelight
    update_cache: yes
    state:        latest
