---
- name: "[cm-30] Add relevant sensors to suricata_hosts group"
  add_host:
    name: "{{ item }}"
    groups: suricata_hosts
  changed_when: false
  when:
    - "hostvars[item].suricata_update_enable|d('disabled') == 'local' or item == suricata_update_host"
  with_items: "{{ groups['all'] }}"

- name: "[cm-31] suricata_hosts group members"
  debug:
    msg: |
      "suricata_hosts group members"
      "{{ groups.suricata_hosts }}"
  when: "groups.suricata_hosts is defined"
  tags: [never, debug]

- name: "[cm-32] Add relevant sensors to suricata_local group"
  add_host:
    name: "{{ item }}"
    groups: suricata_local
  changed_when: false
  when:
    - hostvars[item].suricata_update_enable|d('disabled') == 'local'
  with_items: "{{ groups['all'] }}"

- name: "[cm-33] suricata_local group members "
  debug:
    msg: |
      "suricata_local group members"
      "{{ groups.suricata_local }}"
  when: "groups.suricata_local is defined"
  tags: [never, debug]

- name: "[cm-34] Add relevant sensors to suricata_remote group"
  add_host:
    name: "{{ item }}"
    groups: suricata_remote
  changed_when: false
  when:
    - hostvars[item].suricata_update_enable|d('disabled') == 'remote'
  with_items: "{{ groups['all'] }}"

- name: "[cm-35] suricata_remote group members"
  debug:
    msg: |
      "suricata_remote group members"
      "{{ groups.suricata_remote }}"
  when: "groups.suricata_remote is defined"
  tags: [never, debug]

- name: "[cm-36] Add relevant hosts to main_hosts group"
  add_host:
    name: "{{ item }}"
    groups: main_hosts
  changed_when: false
  when:
    - "((hostvars[item].ansible_connection|d('ssh') != 'local' and item == suricata_update_host) or
      (hostvars[item].ansible_connection|d('ssh') != 'local' and item == cron_job_host) or
      (item == 'localhost'))"
  with_items: "{{ groups['all'] }}"

- name: "[cm-37] main_host group members"
  debug:
    msg: |
      "main_hosts group members"
      "{{ groups.main_hosts }}"
  when: "groups.main_hosts is defined"
  tags: [never, debug]
