
---
- name: "[cm-60] Gather Facts for suricata-update"
  setup:
    filter: ansible_local
    gather_subset: "!all"
  when:
    - "inventory_hostname == suricata_update_host or
      'suricata_local' in group_names or
      'suricata_remote' in group_names"
    - "'physical_sensors' not in group_names"

- name: "[cm-61] "
  pause:
    seconds: 5
    prompt: |
      #################################################################
      #################################################################
      The Suricata-update_host for remote hosts has not been configured
      The following host MUST EXIT NOW!
      "{{ groups.suricata_remote | to_nice_json }}"
      #################################################################
      #################################################################
  when:
    - "hostvars[suricata_update_host]['ansible_local']['corelight_ansible_roles'].suricata_update.config|d('failed') != 'success'"

- name: "[cm-62] Cannot run suricata-update"
  debug:
    msg: "suricata_update_host not configured for {{ inventory_hostname }}"
  when:
    - "'suricata_remote' in group_names or inventory_hostname == suricata_update_host"
    - "hostvars[suricata_update_host]['ansible_local']['corelight_ansible_roles'].suricata_update.config|d('failed') != 'success'"
  failed_when: true

- name: "[cm-] Software Sensor not ready"
  debug:
    msg: "Software Sensor with Suricata not configured on {{ inventory_hostname }}"
  when:
    - "'suricata_remote' in group_names"
    - "'software_sensors' in group_names"
    - "ansible_local['corelight_ansible_roles'].softsensor.config|d('failed') != 'success'"
  failed_when: true

- name: "[cm-63] Include tests for suricata-update on a sensor"
  include_tasks: fc-suricata-update-run-on-sensor.yml
  when:
    - "'suricata_local' in group_names"
    - "ansible_local.corelight_ansible_roles.suricata_update.config|d('failed') != 'success'"

- name: "[cm-64] "
  pause:
    seconds: 5
    prompt: |
      The following host are a GO!
        unless they are stopped now
      "{{ ansible_play_batch | to_nice_json }}"
