---
- name: "[cm-10] Load vars"
  include_vars:
    dir: "{{ playbook_dir }}/common"
    ignore_files:
      - "example-secrets.yml"
      - "example-main-vars.yml"
    ignore_unknown_extensions: yes
    extensions:
      - ""
      - "yaml"
      - "yml"
      - "json"

#
# # Prep common role vars/main for host history facts
# - name: "[cm-10] List vars files in common to be copied"
#   find:
#     paths:
#       - "{{ playbook_dir }}/common"
#     use_regex: yes
#     patterns: "^(?!(secrets.*|example.*)).*-vars.yml"
#   register: copy_var_files
#
# # Copy external playbook_dir/common/vars/ to common/vars/fragments/
# - name: "[cm-11] Copy any vars files in external common/vars to role"
#   copy:
#     src: "{{ item }}"
#     dest: "{{ role_path }}/vars/fragments/"
#     mode: '0644'
#   with_items: "{{ copy_var_files.files | json_query('[*].path') }}"
#
# Create common/vars/main.yml fragments
- name: "[cm-12] create common/vars/fragments/1main.yml comment"
  lineinfile:
    path: "{{ role_path }}/vars/fragments/1main.yml"
    line: "# Assembled from ./fragments/*.yml files"
    regex: "^# Assembled from \\./fragments/\\*\\.yml files"
    create: yes
    insertbefore: BOF
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "[cm-13] Create common_role_path var in common/vars/fragments/1main.yml"
  lineinfile:
    path: "{{ role_path }}/vars/fragments/1main.yml"
    line: "common_role_path: {{ role_path }}"
    regex: "^common_role_path: {{ role_path }}"
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "[cm-14] create common/vars/fragments/host_facts/1main.yml dictionary"
  lineinfile:
    path: "{{ role_path }}/vars/fragments/host_facts/1main.yml"
    line: "hosts_history:"
    regexp: "^hosts_history:"
    insertafter: "EOF"
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    create: yes

# # Do I need the host facts in common/vars/main.yml
# - name: "[cm-15] Re-assemble common/vars/host_facts.yml"
#   assemble:
#     src: "{{ role_path }}/vars/fragments/host_facts"
#     dest: "{{ role_path }}/vars/fragments/host_facts.yml"

- name: "[cm-16] Re-assemble common/vars/main.yml"
  assemble:
    src: "{{ role_path }}/vars/fragments/"
    dest: "{{ role_path }}/vars/main.yml"
    mode: '0644'

- name: "[cm-17] Include prep-role tasks"
  include_tasks: prep-roles.yml
  loop: "{{ role_name_fact }}"
  loop_control:
    loop_var: outer_item
