---
- block:
    # Create/Set facts on remote hosts in ini format
    - name: "[cm-40] Create Corelight-Ansible-Role /etc/ansible directory"
      file:
        path: /etc/ansible
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: yes
      when:
        - "'physical_sensors' not in group_names"

    - name: "[cm-41] Create Corelight-Ansible-Role /etc/ansible/facts.d directory"
      file:
        path: /etc/ansible/facts.d
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: yes

    - name: "[cm-42] Create Corelight-Ansible-Role {{ fact_value }} facts {{ role_name }}"
      community.general.ini_file:
        path: "/etc/ansible/facts.d/corelight_ansible_roles.fact"
        section: "{{ fact_section }}"
        option: "{{ fact_option }}"
        value: "{{ fact_value }}"
        mode: '0644'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: yes

    - name: "[cm-43] Create Corelight-Ansible-Role facts date"
      community.general.ini_file:
        path: "/etc/ansible/facts.d/corelight_ansible_roles.fact"
        section: "{{ fact_section }}"
        option: "{{ fact_option }}_last_run"
        value: "{{ now() }}"
      become: yes
      changed_when: false

    - name: "[cm-44] Create Corelight-Ansible-Role failed_task facts {{ role_name }}"
      community.general.ini_file:
        path: "/etc/ansible/facts.d/corelight_ansible_roles_failed_tasks.ini"
        section: "{{ fact_section }}"
        option: "{{ fact_option }}_failed_task"
        value: "{{ failed_task }}"
        mode: '0644'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: yes

    - name: "[cm-45] Create failed_task stdout {{ role_name }}"
      community.general.ini_file:
        path: "/etc/ansible/facts.d/corelight_ansible_roles_failed_tasks.ini"
        section: "{{ fact_section }}_failed_task_details"
        option: failed_task_result
        value: "{{ ansible_failed_result.stderr_lines|d() | to_nice_yaml }}"
        state: "{{ failed_state }}"
      become: yes
      changed_when: false

    # do we need the host facts in common/vars section ??
    # Create/Set facts in local common role vars in yaml format
    # - name: "[cm-36] Set common/vars/fragments {{ inventory_hostname }} history facts for {{ role_name }}"
    #   lineinfile:
    #     path: "{{ common_role_path }}/vars/fragments/host_facts/{{ inventory_hostname }}.yml"
    #     line: "  {{ inventory_hostname }}:"
    #     regexp: "^  {{ inventory_hostname }}:"
    #     insertbefore: "BOF"
    #     mode: '0644'
    #     owner: "{{ ansible_user }}"
    #     group: "{{ ansible_user }}"
    #     create: yes
    #   become: yes
    #   delegate_to: localhost
    #
    # - name: "[cm-37] Set common/vars/fragments {{ inventory_hostname }} history facts for {{ role_name }}"
    #   lineinfile:
    #     path: "{{ common_role_path }}/vars/fragments/host_facts/{{ inventory_hostname }}.yml"
    #     line: "    {{ fact_section }}_{{ fact_option }}: {{ fact_value }}"
    #     regexp: "^    {{ fact_section }}_{{ fact_option }}:"
    #     insertafter: "^  {{ inventory_hostname }}:"
    #   become: yes
    #   delegate_to: localhost
    #
    # - name: "[cm-39] Set common/vars/fragments {{ inventory_hostname }} history facts for {{ role_name }}"
    #   lineinfile:
    #     path: "{{ common_role_path }}/vars/fragments/host_facts/{{ inventory_hostname }}.yml"
    #     line: "    {{ fact_section }}_{{ fact_option }}_failed_task: '{{ failed_task }}'"
    #     regexp: "^    {{ fact_section }}_{{ fact_option }}_failed_task:"
    #     insertafter: "^    {{ fact_section }}_{{ fact_option }}:"
    #   become: yes
    #   delegate_to: localhost
    #
    # - name: "[cm-40] Set common/vars/fragments {{ inventory_hostname }} history facts for {{ role_name }}"
    #   lineinfile:
    #     path: "{{ common_role_path }}/vars/fragments/host_facts/{{ inventory_hostname }}.yml"
    #     line: "    {{ fact_section }}_{{ fact_option }}_last_run: {{ now() }}"
    #     regexp: "^    {{ fact_section }}_{{ fact_option }}_last_run"
    #     insertafter: "^    {{ fact_section }}_{{ fact_option }}_failed_task:"
    #   become: yes
    #   delegate_to: localhost
    #
    # # Re-assemble common/vars/host_facts.yml
    # - name: "[cm-41] Re-assemble common/vars/main.yml"
    #   assemble:
    #     src: "{{ common_role_path }}/vars/fragments/host_facts"
    #     dest: "{{ common_role_path }}/vars/fragments/host_facts.yml"
    #   delegate_to: localhost
    #   run_once: yes
    #
    # # Re-assemble common/vars/main.yml
    # - name: "[cm-41] Re-assemble common/vars/main.yml"
    #   assemble:
    #     src: "{{ common_role_path }}/vars/fragments"
    #     dest: "{{ common_role_path }}/vars/main.yml"
    #   delegate_to: localhost
    #   run_once: yes

    # Create/Set facts in local role vars
    - name: "[cm-46] Set role /vars/fragments {{ inventory_hostname }} history facts for {{ role_name }}"
      lineinfile:
        path: "{{ role_path }}/vars/fragments/{{ inventory_hostname }}.yml"
        line: "  {{ inventory_hostname }}:"
        regexp: "^  {{ inventory_hostname }}:"
        insertbefore: BOF
        mode: '0644'
        create: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: yes
      delegate_to: localhost

    - name: "[cm-47] Set role /vars/fragments {{ inventory_hostname }} history facts for {{ role_name }}"
      lineinfile:
        path: "{{ role_path }}/vars/fragments/{{ inventory_hostname }}.yml"
        line: "    {{ fact_section }}_{{ fact_option }}: {{ fact_value }}"
        regexp: "^    {{ fact_section }}_{{ fact_option }}:"
        insertafter: "^  {{ inventory_hostname }}:"
      become: yes
      delegate_to: localhost

    # - name: "[cm-48] Set role /vars/fragments {{ inventory_hostname }} history facts for {{ role_name }}"
    #   lineinfile:
    #     path: "{{ role_path }}/vars/fragments/{{ inventory_hostname }}.yml"
    #     line: "    {{ fact_section }}_{{ fact_option }}_failed_task: '{{ failed_task }}'"
    #     regexp: "^    {{ fact_section }}_{{ fact_option }}_failed_task:"
    #     insertafter: "^    {{ fact_section }}_{{ fact_option }}:"
    #   become: yes
    #   delegate_to: localhost

    - name: "[cm-49] Set role /vars/fragments {{ inventory_hostname }} history facts for {{ role_name }}"
      lineinfile:
        path: "{{ role_path }}/vars/fragments/{{ inventory_hostname }}.yml"
        line: "    {{ fact_section }}_{{ fact_option }}_last_run: {{ now() }}"
        regexp: "^    {{ fact_section }}_{{ fact_option }}_last_run"
        insertafter: "^    {{ fact_section }}_{{ fact_option }}:"
      become: yes
      delegate_to: localhost

    # Re-assemble role vars/main.yml
    - name: "[cm-50] Re-assemble role vars/main.yml"
      assemble:
        src: "{{ role_path }}/vars/fragments"
        dest: "{{ role_path }}/vars/main.yml"
        mode: '0644'
      delegate_to: localhost
      run_once: yes
  when:
  - "'physical_sensors' not in group_names"
