---
- name:           "centos: Install pip3"
  yum:
    name:         python3-pip
    state:        latest

- name:           "centos: Enable CentOS Extra repos"
  yum:
    name:         epel-release
    state:        latest
  when: 
    - "ansible_distribution_major_version == '7'"

- name:           "centos: Install python-setuptools"
  yum:
    name:         python-setuptools
    state:        latest
  when: 
    - "ansible_distribution_major_version == '7'"

- name:           "centos: Install pip2"
  yum:
    name:         python-pip
    state:        latest
  when: 
    - "ansible_distribution_major_version == '7'"

- name:             "centos: Install Suricata-update"
  pip:
    name:           suricata-update
    state:          latest
    executable:     pip3
    extra_args:     --upgrade --user
  become:           no
  when: 
    - "ansible_distribution_major_version == '7'"

- name:             "centos: Install Suricata-update"
  pip:
    name:           suricata-update
    state:          latest
    executable:     pip3
  become:           no
  when: 
    - "ansible_distribution_major_version != '7'"
