- name:                 Collect physical/virtual sensor Suricata version
  include_tasks:        collect_suricata_ph_versions.yml
  when:
    - ('physical_sensors' in group_names or 'virtual_sensors' in group_names)

- name:                 Collect software sensor Suricata version
  include_tasks:        collect_suricata_sw_versions.yml
  when:
    - "'software_sensors' in group_names"

- name:                 Add relevant sensors to suricata_remote group
  group_by:
    key:                suricata_remote

- name:                 Set Version Facts
  set_fact:
    suricata_version:   "{{ suricata_status.stdout_lines | select('match', '^(.)*?version') | list | regex_replace('[^0-9]*([0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2})(.+)$', '\\1') }}"
    cacheable:          yes

- name:                 Write Suricata Versions to file
  template:
    src:                "suricata_versions.j2"
    dest:               "{{ role_path }}/vars/suricata_version_facts.json"
    mode:               0644
  delegate_to:          localhost
  run_once:             true

- include_vars:
    file:               suricata_version_facts.json

- name:                 Remove duplicate versions
  set_fact:
    suricata_versions:  "{{ hostvars[inventory_hostname]['suricata_versions'] | unique }}"
  delegate_to:          localhost
  run_once:             true

- name:                 Suricata versions
  debug:
    msg:                "{{ suricata_versions }}"
  run_once:             true