- name:                 "collect_suricata_versions: Collect physical/virtual sensor Suricata version"
  include_tasks:        collect_suricata_ph_versions.yml
  when:
    - ('physical_sensors' in group_names or 'virtual_sensors' in group_names)

- name:                 "collect_suricata_versions: Collect software sensor Suricata version"
  include_tasks:        collect_suricata_sw_versions.yml
  when:
    - "'software_sensors' in group_names"

- name:                 "collect_suricata_versions: Add relevant sensors to suricata_remote group"
  group_by:
    key:                suricata_remote

- name:                 "collect_suricata_versions: Set Version Facts"
  set_fact:
    suricata_version:   "{{ suricata_status.stdout_lines | select('match', '^(.)*?version') | list | regex_replace('[^0-9]*([0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2})(.+)$', '\\1') }}"
    cacheable:          yes
