---
- name:           "debian_cron: Install required packages"
  apt:
    pkg:
    - git
    update_cache: yes
    state:        latest
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"

- name:           "debian_cron: Add Ansible Repository"
  apt_repository:
    repo:         'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main'
    update_cache: yes
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"

- name:           "debian_cron: Add apt-key"
  apt_key:
    keyserver:    keyserver.ubuntu.com
    id:           93C4A3FD7BB9C367
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"

- name:           "debian_cron: Install ansible"
  apt:
    name:         ansible
    state:        latest
    autoclean:    yes
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"

- name:           "debian_cron: Install corelight-client"
  pip:
    name:         corelight-client
    state:        latest
    executable:   pip3
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"
