---
- name:             Load vars
  include_vars:
    file:           '{{ item }}'
  with_items:
    - "{{ secrets_path }}"
    - "{{ main_vars_path }}"

- name:             "main: Gather local facts"
  setup:
  when:
    - "ansible_connection == 'local'"

- name:             "main: Gather localhost facts"
  setup:
  delegate_to:      localhost
  run_once:         true
  when:
    - "ansible_connection != 'local'"

- name:             "main: Gather Software Sensor facts"
  setup:
  ignore_errors:    true
  when:
    - ('software_sensors' in group_names or 'suricata_update_host' in group_names)
    - "suricata_update_enable != 'disabled'"

# suricata-update install
- name:             "main: Include Suricata-update Host Install tasks"
  include_tasks:    suricata-update-install.yml
  when:
    - "suricata_update_host == inventory_hostname"
    - ('software_sensors' in group_names or 'suricata_update_host' in group_names)
    - only_perform_cron_job_tasks is false

# suricata-update config
- name:             "main: Include Suricata-update Host config tasks"
  include_tasks:    suricata-update-config.yml
  when:
    - "suricata_update_host == inventory_hostname"
    - ('software_sensors' in group_names or 'suricata_update_host' in group_names)
    - only_perform_cron_job_tasks is false

- name:             "main: Include collect suricata version tasks"
  include_tasks:    collect_suricata_versions.yml
  when:
    - (suricata_update_enable == 'remote' or (suricata_update_host == inventory_hostname and 'software_sensors' in group_names))
    - only_perform_cron_job_tasks is false

- name:             "main: Include suricata-update-run tasks"
  include_tasks:    suricata-update-run.yml
  when:
    - "suricata_update_host == inventory_hostname"
    - only_perform_cron_job_tasks is false

# Install suricata-update on a stand-a-lone software sensor
# - name:             "main: Include suricata-update-local tasks"
#   include_tasks:    suricata-update-local.yml
#   when:
#     - "suricata_update_host != inventory_hostname"
#     - "suricata_update_enable == 'local'"
#     - "'software_sensors' in group_names"
#     - "'suricata_update_host' not in group_names"
#     - (target == inventory_hostname or target == 'all')
#     - only_perform_cron_job_tasks is false

- name:             "main: Include Update Suricata Address Groups Tasks"
  include_tasks:    update-suricata-address-groups.yml
  when:
    - (suricata_enable is true or ('physical_sensors' in group_names and suricata_update_enable != 'disabled'))
    - (target == inventory_hostname or target == 'all')
    - only_perform_cron_job_tasks is false
    - suricata_address_groups is defined

- name:             "main: Include Suricata Rules Clients Tasks"
  include_tasks:    suricata-rules-clients.yml
  when:
    - "suricata_update_enable == 'remote'"
    - (target == inventory_hostname or target == 'all' or inventory_hostname == suricata_update_host or inventory_hostname == cron_job_host)
    - only_perform_cron_job_tasks is false

- name:             "main: Message"
  debug:
    msg:            "Cron Job Tasks"
  run_once:         true
  when: perform_cron_job_tasks is true

- name:             "main: Include Cron Job Tasks for localhost"
  include_tasks:    cron_localhost.yml
  when:
    - "cron_job_host == 'localhost'"
    - "suricata_update_host != 'localhost'"
    - perform_cron_job_tasks is true

- name:             "main: Include Cron Job Tasks for non-localhost"
  include_tasks:    cron_update_host.yml
  when:
    - cron_job_host == inventory_hostname
    - ('software_sensors' in group_names or 'suricata_update_host' in group_names)
    - perform_cron_job_tasks is true
