---
- name:           "redhat_cron: Install git"
  yum:
    name:         git
    update_cache: yes
    state:        latest
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"

- name:           "redhat_cron: Install ansible"
  pip:
    name:         ansible
    state:        latest
    executable:   pip3
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"

- name:           "redhat_cron: Install corelight-client"
  pip:
    name:         corelight-client
    state:        latest
    executable:   pip3
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"
