---
- name:           "rhel: Install pip3 - RHEL / CentOS"
  yum:
    name:         python3-pip
    state:        latest

- name:           "centos: Enable CentOS Extra repos - CentOS7 only"
  yum:
    name:         epel-release
    state:        latest
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version == '7'"

- name:           "centos: Install python-setuptools - CentOS7 only"
  yum:
    name:         python-setuptools
    state:        latest
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version == '7'"

- name:           "rhel: Install libselinux-python on RHEL7"
  yum:
    name:         libselinux-python
    state:        latest
  when:
    - "ansible_distribution_major_version == '7'"

- name:           "rhel: Install pip2 - RHEL7 / CentOS7 only"
  yum:
    name:         python-pip
    state:        latest
  when: 
    - "ansible_distribution_major_version == '7'"
