---
- name:           "rhel: Install pip3 - RHEL / CentOS"
  yum:
    name:         python3-pip
    state:        latest
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"

- name:           "centos: Enable CentOS Extra repos - CentOS7 only"
  yum:
    name:         epel-release
    state:        latest
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version == '7'"
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"

- name:           "centos: Install python-setuptools - CentOS7 only"
  yum:
    name:         python-setuptools
    state:        latest
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version == '7'"
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"

- name:           "rhel: Install libselinux-python on RHEL7 / CentOS7"
  yum:
    name:         libselinux-python
    state:        latest
  when:
    - "ansible_distribution_major_version == '7'"
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"

- name:           "rhel: Install pip2 - RHEL7 / CentOS7 only"
  yum:
    name:         python-pip
    state:        latest
  when: 
    - "ansible_distribution_major_version == '7'"
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"
