---
- name:                 "collect_suricata_versions: Write Suricata Versions to file"
  template:
    src:                "suricata_versions.j2"
    dest:               "{{ role_path }}/vars/suricata_version_facts.json"
    mode:               0644
  delegate_to:          localhost
  when:
    - "ansible_connection != 'local'"

- name:                 "collect_suricata_versions: Write Suricata Versions to file local"
  template:
    src:                "suricata_versions.j2"
    dest:               "{{ role_path }}/vars/suricata_version_facts.json"
    mode:               0644
  when:
    - "ansible_connection == 'local'"

- name:                 "collect_suricata_versions: include version vars"
  include_vars:
    file:               suricata_version_facts.json

- name:                 "collect_suricata_versions: Remove duplicate versions"
  set_fact:
    suricata_versions:  "{{ hostvars[inventory_hostname]['suricata_versions'] | unique }}"
  delegate_to:          localhost
  when:
    - "ansible_connection != 'local'"

- name:                 "collect_suricata_versions: Remove duplicate versions local"
  set_fact:
    suricata_versions:  "{{ hostvars[inventory_hostname]['suricata_versions'] | unique }}"
  when:
    - "ansible_connection == 'local'"

- name:                 "collect_suricata_versions: Suricata versions"
  debug:
    msg:                "{{ suricata_versions }}"
  run_once:             true

# Suricata-update per version
- name:             "suricata-update-run: Run Suricata-update for each version"
  include_tasks:    suricata-update-per-version.yml
  loop:             "{{ suricata_versions }}"

- name:             "suricata-update-run: Copy Suricata-update Rules to Corelight-Suricata Rule folder"
  copy:
    remote_src:     yes
    src:            "{{ suricata_update_path }}/rules/{{ suricata_version }}/suricata.rules"
    dest:           "{{ suricata_rule_path }}"
    mode:           0644
  when:
    - ('suricata_update_host' not in group_names)
  register:         results9

- debug:
    var:            results9.stdout_lines

# copy 
- name:             "suricata-update-run: Fetch new suricata.rules file"
  copy:
    src:            "{{ suricata_update_path }}/rules/{{ item }}/suricata.rules"
    dest:           "{{ role_path }}/files/{{ item }}/"
    mode:           0644
  with_items:       "{{ suricata_versions }}"
  become:           no
  when:
    - "ansible_connection == 'local'"

#fetch
- name:             "suricata-update-run: Fetch new suricata.rules file"
  fetch:
    src:            "{{ suricata_update_path }}/rules/{{ item }}/suricata.rules"
    dest:           "{{ role_path }}/files/{{ item }}/"
    flat:           yes
  with_items:       "{{ suricata_versions }}"
  become:           no
  when:
    - "ansible_connection != 'local'"
