---
- name:           "ubuntu_cron: Install required packages"
  apt:
    pkg:
    - software-properties-common
    - git
    update_cache: yes
    state:        latest
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"

- name:           "ubuntu_cron: Add Ansible Repository"
  apt_repository:
    repo:         'ppa:ansible/ansible'
    update_cache: yes
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"

- name:           "ubuntu_cron: Install ansible"
  apt:
    name:         ansible
    update_cache: yes
    state:        latest
    autoclean:    yes
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"

- name:           "ubuntu_cron: Install corelight-client"
  pip:
    name:         corelight-client
    state:        latest
    executable:   pip3
  environment:
    http_proxy:     "{{ http_proxy_env | default() }}"
    https_proxy:    "{{ https_proxy_env | default() }}"
