# updated
---
- name:           "redhat: Check for zkg in sudoers path"
  lineinfile:
    path:         /etc/sudoers
    regexp:       '^(Defaults\s+secure_path\s+=\s+)(.*:)?/usr/local/bin(:.*)?$'
    state:        absent
  check_mode:     yes
  changed_when:   false
  register:       sudoers_path

- name:           "redhat: Add zkg to sudoers path"
  lineinfile:
    path:         /etc/sudoers
    regexp:       '^(Defaults\s+secure_path\s+=\s+.*)$'
    line:         '\1:/usr/local/bin'
    state:        present
    create:       yes
    mode:         u=wrx,g=rx,o=rx
    backrefs:     yes
  when:           not sudoers_path.found

- name:           Reset connection to enable PATH change
  meta:           reset_connection
  changed_when:   false
