---
- block:
    - name: "[zkgi-2] Install zkg"
      pip:
        name: zkg
        virtualenv: "{{ virtual_env_dir }}"
        extra_args: --upgrade --upgrade-strategy eager
        virtualenv_command: python3 -m venv
      become: no
      register: results
      environment:
        http_proxy: "{{ http_proxy_env |d() }}"
        https_proxy: "{{ https_proxy_env |d() }}"

    - name: "[zkgi-3] ZKG installation results"
      debug:
        msg: "{{ results.stdout_lines }}"

  always:
    - name: "[zkgi-4] Include set role facts tasks"
      include_tasks: "{{ role_path }}/../common/tasks/set-role-facts.yml"
      vars:
        fact_section: zkg
        fact_option: install
        fact_value: success
        failed_task: none
        failed_state: absent
      when: ansible_failed_task is not defined

  rescue:
    - name: "[zkgi-5] Include set role failed facts tasks"
      include_tasks: "{{ role_path }}/../common/tasks/set-role-facts.yml"
      vars:
        fact_section: zkg
        fact_option: install
        fact_value: failed
        failed_task: "{{ ansible_failed_task.name }}"
        failed_state: present
      when: ansible_failed_task is defined

    - name: "[zkgi-6] Failed task"
      fail:
        msg: |
          "{{ ansible_failed_result.stderr_lines | to_nice_yaml }}"
